#pragma once

typedef enum
{
    MOBJ_GROUP_AMBIENT = 0,
    MOBJ_GROUP_COMMON = 1,
    MOBJ_GROUP_OBSTACLES = 2,
    MOBJ_GROUP_SCENERY = 3,
    MOBJ_GROUP_ENEMIES = 4,
    MOBJ_GROUP_BOSSES = 5,

    MOBJ_GROUP_COUNT
} MObjGroup;

typedef enum
{
    MOBJ_ID_BEACH_WATER = 1,
    MOBJ_ID_FALLS_WATER_DST = 2,
    MOBJ_ID_TOWN_WATER = 3,
    //MOBJ_ID_MARIO_WATER = 4, //only in the beta
    MOBJ_ID_WATER_SPLASH = 5,
    MOBJ_ID_YOSHI_WATER = 6,
    //MOBJ_ID_KOOPA_LAVA = 7, //only in the beta
    MOBJ_ID_AMBIENT_SFX_EMITTER = 8, //fig-8 and mario circuit crowd noise and yoshi falls waterfall sound
    MOBJ_ID_HYUDORO_WATER = 9,
    MOBJ_ID_BIRD_SFX_EMITTER = 10, //luigi's mansion and cheep cheep beach
    MOBJ_ID_MISSION_BARRIER = 11, //mkds beta: sfx
    MOBJ_ID_MINI_STAGE_3_WATER = 12,
    MOBJ_ID_PUDDLE = 13,
    MOBJ_ID_LAVA_SPLASH = 14,
    MOBJ_ID_HYUDORO_WATER_SPLASH = 15,
    MOBJ_ID_MR_STAGE_STEAM = 16,

    MOBJ_ID_ITEMBOX = 101,
    MOBJ_ID_DUMMY_POLE = 102,
    MOBJ_ID_WOODBOX_1 = 103,
    MOBJ_ID_COIN = 104,
    MOBJ_ID_BALLOON_CONTROLLER = 105,
    MOBJ_ID_SHINE = 106,
    MOBJ_ID_SHINE_CONTROLLER = 107,
    MOBJ_ID_BALLOON = 108,

    MOBJ_ID_MISSION_GATE = 110,
    MOBJ_ID_UNK_ITEMBOX = 111,
    MOBJ_ID_SHINE_BALLOON = 112, //popup balloon to indicate where a shine is

    MOBJ_ID_MOVE_ITEMBOX = 201,
    MOBJ_ID_KOOPA_BLOCK = 202,
    MOBJ_ID_GEAR = 203,
    MOBJ_ID_BRIDGE = 204,
    MOBJ_ID_SECOND_HAND = 205,
    MOBJ_ID_TEST_CYLINDER = 206,
    MOBJ_ID_PENDULUM = 207,
    MOBJ_ID_ROTARY_ROOM = 208,
    MOBJ_ID_ROTARY_BRIDGE = 209,
    MOBJ_ID_DRAM = 210, //spinning item roulette of waluigi pinball

    MOBJ_ID_BEACH_TREE_1_NOCOL = 301,
    MOBJ_ID_BEACH_TREE_1 = 302,
    MOBJ_ID_EARTHEN_PIPE = 303,
    MOBJ_ID_OPA_TREE_1 = 304,
    MOBJ_ID_OLG_PIPE_1 = 305,
    MOBJ_ID_OLG_MUSH_1 = 306,
    MOBJ_ID_OF6_YOSHI_1 = 307,
    MOBJ_ID_COW = 308,
    MOBJ_ID_NS_CANNON_1 = 309,
    MOBJ_ID_MINI_DOKAN = 310,

    MOBJ_ID_GARDEN_TREE_1 = 312,

    MOBJ_ID_CROSS_TREE_1 = 314,
    MOBJ_ID_TERESA = 315,
    MOBJ_ID_BAKUBAKU = 316, //n64 jumping fish
    MOBJ_ID_TERESA_CONTROLLER = 317,
    MOBJ_ID_BANK_TREE_1 = 318,
    MOBJ_ID_GARDEN_TREE_1_NOCOL = 319,
    MOBJ_ID_CHANDELIER = 320,
    MOBJ_ID_TOWN_TREE_1_NOCOL = 321,
    MOBJ_ID_MARIO_TREE_3 = 322,
    MOBJ_ID_SNOW_TREE_1_NOCOL = 323,
    //MOBJ_ID_PIN_1 = 324, //only in the beta, pinball pin
    MOBJ_ID_TOWN_TREE_1 = 325,
    MOBJ_ID_SNOW_TREE_1 = 326,
    MOBJ_ID_DE_TREE_1_NOCOL = 327,
    MOBJ_ID_DE_TREE_1 = 328,
    MOBJ_ID_BANK_EGG_1 = 329,

    MOBJ_ID_KINO_HOUSE_1 = 331,
    MOBJ_ID_KINO_HOUSE_2 = 332,
    MOBJ_ID_KINO_MOUNT_1 = 333,
    MOBJ_ID_KINO_MOUNT_2 = 334,
    MOBJ_ID_OLA_TREE_1C = 335,
    MOBJ_ID_OSA_TREE_1C = 336,
    MOBJ_ID_PICTURE_1 = 337,
    MOBJ_ID_PICTURE_2 = 338,
    MOBJ_ID_OM6_TREE_1 = 339,
    MOBJ_ID_RAIN_STAR = 340,
    MOBJ_ID_OF6_TREE_NOCOL = 341,
    MOBJ_ID_OF6_TREE = 342,
    MOBJ_ID_TOWN_MONTE = 343,
    MOBJ_ID_AIRSHIP = 344,
    MOBJ_ID_STOP_SIGN = 345,

    MOBJ_ID_KURIBO = 401,
    MOBJ_ID_ROCK = 402,
    MOBJ_ID_DOSSUN = 403,
    MOBJ_ID_STUBBED_404 = 404,
    MOBJ_ID_BUS = 405,
    MOBJ_ID_WANWAN_FIXED = 406,
    MOBJ_ID_WANWAN_CHAIN = 407,
    MOBJ_ID_MKD_EF_BUBBLE = 408,
    MOBJ_ID_CHOROPU = 409,
    MOBJ_ID_CAR = 410,
    MOBJ_ID_PUKUPUKU = 411,
    MOBJ_ID_TRUCK = 412,
    MOBJ_ID_SMAN = 413,
    MOBJ_ID_KANOKE_64 = 414,
    MOBJ_ID_BASABASA = 415,
    MOBJ_ID_BASABASA_SPAWNER = 416,
    MOBJ_ID_NS_KILLER_1 = 417,
    MOBJ_ID_NS_KILLER_2 = 418,
    MOBJ_ID_MOVE_TREE = 419,
    MOBJ_ID_MKD_EF_BURNER = 420,
    MOBJ_ID_WANWAN_MOVE = 421,
    MOBJ_ID_OB_PAKKUN_SF = 422,
    MOBJ_ID_POO = 423,
    MOBJ_ID_BOUND = 424,
    MOBJ_ID_FLIPPER = 425,
    MOBJ_ID_PAKKUN = 426,
    MOBJ_ID_PAKKUN_FIRE = 427,
    MOBJ_ID_CRAB = 428,
    MOBJ_ID_SUN = 429,
    MOBJ_ID_SUN_FIRE_SNAKE = 430,
    MOBJ_ID_FIREBALL_2 = 431,
    MOBJ_ID_IRON_BALL = 432, //puddle in beta mkds
    MOBJ_ID_ROCK_2 = 433,
    MOBJ_ID_SANBO = 434,
    MOBJ_ID_IRON_BALL_NOCOL = 435,
    MOBJ_ID_CREAM = 436,
    MOBJ_ID_BERRY = 437,
    MOBJ_ID_UNK_438_MR_PARTICLE = 438,

    MOBJ_ID_BOSS_DONKETU = 501,
    MOBJ_ID_KING_ICE_DONKETU = 502,
    MOBJ_ID_KURI_KING = 503,
    MOBJ_ID_BOMB_KING = 504,

    MOBJ_ID_IWANTE_L = 507,
    MOBJ_ID_HANACHAN = 508,
    MOBJ_ID_KING_TERESA = 509,
    MOBJ_ID_HANACHAN_BODY_PART = 510,
    MOBJ_ID_UNK_511_MR_PARTICLE = 511,
    MOBJ_ID_IWANTE_CONTROLLER = 512
} MObjId;
